name: flutter_webview_plugin_enhance
description: Plugin that allow Flutter to communicate with a native Webview. Fork from flutter_webview_plugin 0.3.0+2. Support host app handle schemas. Such as "tel", "sms", "alipays", "wechat"...
authors:
- Sheng Peng <lavashengpeng@gmail.com>
homepage: https://github.com/shpeng/flutter_webview_plugin
version: 0.0.1
maintainer: Beck (@shpeng)

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.flutter_webview_plugin
    pluginClass: FlutterWebviewPlugin

dependencies:
  flutter:
    sdk: flutter
